export const items1 = [
  {
    id: 1,
    image: '/Screenshot_1.png',
    link: 'https://web-illa-cloud.netlify.app',
    description: 'web-illa-cloud.netlify.app',
    title: 'Web-illa-cloud',
    framework: 'Vue.js',
    linkFramework: 'https://vuejs.org/',
    imageFramework: '/vue.svg',
    library: 'AOS',
    linkLibrary: 'https://michalsnik.github.io/aos/',
    imageLibrary: '/AOS.svg',
    UIFrameworkT: 'Tailwind CSS',
    linkUIFrameworkT: 'https://tailwindcss.com/',
    imageUIFrameworkT: '/tailwindcss.svg',
    UIFrameworkP: 'PrimeVue',
    linkUIFrameworkP: 'https://primevue.org/',
    imageUIFrameworkP: '/PrimeVue.svg',
    Servis: 'Netlify',
    linkServis: 'https://www.netlify.com/',
    imageServis: '/netlify.svg',
    delay: 100
  },
  {
    id: 2,
    image: '/Screenshot_2.png',
    link: 'https://magedeveloper.netlify.app',
    description: 'magedeveloper.netlify.app',
    title: 'Magedeveloper',
    framework: 'Vue.js',
    linkFramework: 'https://vuejs.org/',
    imageFramework: '/vue.svg',
    library: 'AOS',
    linkLibrary: 'https://michalsnik.github.io/aos/',
    imageLibrary: '/AOS.svg',
    UIFrameworkT: 'Tailwind CSS',
    linkUIFrameworkT: 'https://tailwindcss.com/',
    imageUIFrameworkT: '/tailwindcss.svg',
    UIFrameworkP: 'PrimeVue',
    linkUIFrameworkP: 'https://primevue.org/',
    imageUIFrameworkP: '/PrimeVue.svg',
    Servis: 'Netlify',
    linkServis: 'https://www.netlify.com/',
    imageServis: '/netlify.svg',
    delay: 200
  },
  {
    id: 3,
    image: '/Screenshot_3.png',
    link: 'https://fastgendev.netlify.app',
    description: 'fastgendev.netlify.app',
    title: 'Fastgendev',
    framework: 'Vue.js',
    linkFramework: 'https://vuejs.org/',
    imageFramework: '/vue.svg',
    library: 'AOS',
    linkLibrary: 'https://michalsnik.github.io/aos/',
    imageLibrary: '/AOS.svg',
    UIFrameworkT: 'Tailwind CSS',
    linkUIFrameworkT: 'https://tailwindcss.com/',
    imageUIFrameworkT: '/tailwindcss.svg',
    UIFrameworkP: 'PrimeVue',
    linkUIFrameworkP: 'https://primevue.org/',
    imageUIFrameworkP: '/PrimeVue.svg',
    Servis: 'Netlify',
    linkServis: 'https://www.netlify.com/',
    imageServis: '/netlify.svg',
    delay: 300
  },
  {
    id: 4,
    image: '/Screenshot_4.png',
    link: 'https://vuesneakers747.netlify.app',
    description: 'vuesneakers747.netlify.app',
    title: 'VueSneakers',
    framework: 'Vue.js',
    linkFramework: 'https://vuejs.org/',
    imageFramework: '/vue.svg',
    library: 'AOS',
    linkLibrary: 'https://michalsnik.github.io/aos/',
    imageLibrary: '/AOS.svg',
    UIFrameworkT: 'Tailwind CSS',
    linkUIFrameworkT: 'https://tailwindcss.com/',
    imageUIFrameworkT: '/tailwindcss.svg',
    UIFrameworkP: 'PrimeVue',
    linkUIFrameworkP: 'https://primevue.org/',
    imageUIFrameworkP: '/PrimeVue.svg',
    Servis: 'Netlify',
    linkServis: 'https://www.netlify.com/',
    imageServis: '/netlify.svg',
    delay: 400
  },
  {
    id: 5,
    image: '/Screenshot_5.png',
    link: 'https://hyperwebdev.netlify.app',
    description: 'hyperwebdev.netlify.app',
    title: 'Hyperwebdev',
    framework: 'Vue.js',
    linkFramework: 'https://vuejs.org/',
    imageFramework: '/vue.svg',
    library: 'AOS',
    linkLibrary: 'https://michalsnik.github.io/aos/',
    imageLibrary: '/AOS.svg',
    UIFrameworkT: 'Tailwind CSS',
    linkUIFrameworkT: 'https://tailwindcss.com/',
    imageUIFrameworkT: '/tailwindcss.svg',
    UIFrameworkP: 'PrimeVue',
    linkUIFrameworkP: 'https://primevue.org/',
    imageUIFrameworkP: '/PrimeVue.svg',
    Servis: 'Netlify',
    linkServis: 'https://www.netlify.com/',
    imageServis: '/netlify.svg',
    delay: 500
  },
  {
    id: 6,
    image: '/Screenshot_11.png',
    link: 'https://webupstash.netlify.app/',
    description: 'webupstash.netlify.app',
    title: 'Upstash',
    framework: 'Vue.js',
    linkFramework: 'https://vuejs.org/',
    imageFramework: '/vue.svg',
    library: 'AOS',
    linkLibrary: 'https://michalsnik.github.io/aos/',
    imageLibrary: '/AOS.svg',
    UIFrameworkT: 'Tailwind CSS',
    linkUIFrameworkT: 'https://tailwindcss.com/',
    imageUIFrameworkT: '/tailwindcss.svg',
    UIFrameworkP: 'PrimeVue',
    linkUIFrameworkP: 'https://primevue.org/',
    imageUIFrameworkP: '/PrimeVue.svg',
    Servis: 'Netlify',
    linkServis: 'https://www.netlify.com/',
    imageServis: '/netlify.svg',
    delay: 500
  }
];
export const items2 = [
  {
    id: 1,
    image: '/Screenshot_6.png',
    link: 'https://31-saa-s.vercel.app/',
    description: '31-saa-s.vercel.app',
    title: '31-saa-s',
    framework: 'Next.js',
    linkFramework: 'https://nextjs.org/',
    imageFramework: '/Next.js.svg',
    frameworkR: 'React.js',
    linkFrameworkR: 'https://reactjs.org/',
    imageFrameworkR: '/React.svg',
    library: 'AOS',
    linkLibrary: 'https://michalsnik.github.io/aos/',
    imageLibrary: '/AOS.svg',
    UIFrameworkT: 'Tailwind CSS',
    linkUIFrameworkT: 'https://tailwindcss.com/',
    imageUIFrameworkT: '/tailwindcss.svg',
    UIFrameworkS: 'shadcn/ui',
    linkUIFrameworkS: 'https://ui.shadcn.com/',
    imageUIFrameworkS: '/shadcn-ui.svg',
    UIFrameworkR: 'Radix UI',
    linkUIFrameworkR: 'https://www.radix-ui.com/',
    imageUIFrameworkR: '/Radix UI.svg',
    Servis: 'Vercel',
    linkServis: 'https://vercel.com/',
    imageServis: '/vercel.svg',
    delay: 100
  },
  {
    id: 2,
    image: '/Screenshot_7.png',
    link: 'https://mirror-world-seven.vercel.app/',
    description: 'mirror-world-seven.vercel.app',
    title: 'Mirror-world',
    framework: 'Next.js',
    linkFramework: 'https://nextjs.org/',
    imageFramework: '/Next.js.svg',
    frameworkR: 'React.js',
    linkFrameworkR: 'https://reactjs.org/',
    imageFrameworkR: '/React.svg',
    library: 'AOS',
    linkLibrary: 'https://michalsnik.github.io/aos/',
    imageLibrary: '/AOS.svg',
    UIFrameworkT: 'Tailwind CSS',
    linkUIFrameworkT: 'https://tailwindcss.com/',
    imageUIFrameworkT: '/tailwindcss.svg',
    UIFrameworkS: 'shadcn/ui',
    linkUIFrameworkS: 'https://ui.shadcn.com/',
    imageUIFrameworkS: '/shadcn-ui.svg',
    UIFrameworkR: 'Radix UI',
    linkUIFrameworkR: 'https://www.radix-ui.com/',
    imageUIFrameworkR: '/Radix UI.svg',
    Servis: 'Vercel',
    linkServis: 'https://vercel.com/',
    imageServis: '/vercel.svg',
    delay: 200
  },
  {
    id: 3,
    image: '/Screenshot_8.png',
    link: 'https://next-js-pizza-sigma.vercel.app/',
    description: 'next-js-pizza-sigma.vercel.app',
    hidden: 'xl:block hidden',
    title: 'Next-Pizza',
    framework: 'Next.js',
    linkFramework: 'https://nextjs.org/',
    imageFramework: '/Next.js.svg',
    frameworkR: 'React.js',
    linkFrameworkR: 'https://reactjs.org/',
    imageFrameworkR: '/React.svg',
    library: 'AOS',
    linkLibrary: 'https://michalsnik.github.io/aos/',
    imageLibrary: '/AOS.svg',
    UIFrameworkT: 'Tailwind CSS',
    linkUIFrameworkT: 'https://tailwindcss.com/',
    imageUIFrameworkT: '/tailwindcss.svg',
    UIFrameworkS: 'shadcn/ui',
    linkUIFrameworkS: 'https://ui.shadcn.com/',
    imageUIFrameworkS: '/shadcn-ui.svg',
    UIFrameworkR: 'Radix UI',
    linkUIFrameworkR: 'https://www.radix-ui.com/',
    imageUIFrameworkR: '/Radix UI.svg',
    Servis: 'Vercel',
    linkServis: 'https://vercel.com/',
    imageServis: '/vercel.svg',
    titleServer: 'Server',
    Server: 'Prisma',
    linkServer: 'https://www.prisma.io/',
    imageServer: '/Prisma.svg',
    ServerS: 'Supabase',
    linkServerS: 'https://www.supabase.io/',
    imageServerS: '/Supabase.svg',
    delay: 300
  },

  {
    id: 4,
    image: '/Screenshot_9.png',
    link: 'https://lesson-english2-two.vercel.app/',
    description: 'lesson-english2-two.vercel.app',
    title: 'Lesson-English',
    framework: 'Next.js',
    linkFramework: 'https://nextjs.org/',
    imageFramework: '/Next.js.svg',
    frameworkR: 'React.js',
    linkFrameworkR: 'https://reactjs.org/',
    imageFrameworkR: '/React.svg',
    library: 'AOS',
    linkLibrary: 'https://michalsnik.github.io/aos/',
    imageLibrary: '/AOS.svg',
    UIFrameworkT: 'Tailwind CSS',
    linkUIFrameworkT: 'https://tailwindcss.com/',
    imageUIFrameworkT: '/tailwindcss.svg',
    UIFrameworkS: 'shadcn/ui',
    linkUIFrameworkS: 'https://ui.shadcn.com/',
    imageUIFrameworkS: '/shadcn-ui.svg',
    UIFrameworkR: 'Radix UI',
    linkUIFrameworkR: 'https://www.radix-ui.com/',
    imageUIFrameworkR: '/Radix UI.svg',
    Servis: 'Vercel',
    linkServis: 'https://vercel.com/',
    imageServis: '/vercel.svg',
    delay: 400
  },
  {
    id: 5,
    image: '/Screenshot_10.png',
    link: 'https://personalwebfrontend.vercel.app/',
    description: 'personalwebfrontend.vercel.app',
    title: 'PersonalWeb',
    framework: 'Next.js',
    linkFramework: 'https://nextjs.org/',
    imageFramework: '/Next.js.svg',
    frameworkR: 'React.js',
    linkFrameworkR: 'https://reactjs.org/',
    imageFrameworkR: '/React.svg',
    library: 'AOS',
    linkLibrary: 'https://michalsnik.github.io/aos/',
    imageLibrary: '/AOS.svg',
    UIFrameworkT: 'Tailwind CSS',
    linkUIFrameworkT: 'https://tailwindcss.com/',
    imageUIFrameworkT: '/tailwindcss.svg',
    UIFrameworkS: 'shadcn/ui',
    linkUIFrameworkS: 'https://ui.shadcn.com/',
    imageUIFrameworkS: '/shadcn-ui.svg',
    UIFrameworkR: 'Radix UI',
    linkUIFrameworkR: 'https://www.radix-ui.com/',
    imageUIFrameworkR: '/Radix UI.svg',
    Servis: 'Vercel',
    linkServis: 'https://vercel.com/',
    imageServis: '/vercel.svg',
    delay: 500
  }
];
